# Site information
site_name: Scientific Computing & Numerical Analysis

# Configuration
theme:
  name: material
  favicon: assets/images/favicon1.svg
  logo: assets/images/favicon3.svg
  palette: 
    - scheme: default
      # primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      # primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - toc.integrate

# Extension

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Naviation
nav:
  - 'Overview': index.md
  - 'Part 1: Basics':
    - Section_1/index.md
    - 'Algebra with Matrix': Section_1/algebra_with_matrix.md
  - 'Linear Algebra':
    - Section_2/index.md
  - 'Differential Calculus':
    - Section_3/index.md
  - 'Fast Fourier Transform':
    - Section_4/index.md
  - 'Data Fitting & Optimization':
    - Section_5/index.md


# Copyright
copyright: Copyright &copy; 2021 - 2022 Lin Deng

# Extra information
extra:
  generator: false
  alternate:
    - name: 中文
      link: /cn/
      lang: cn
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/linchrisdeng/notes-Scientific-Computing
      name: GitHub

